name: virtual_monitor_stream_pro
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.0.0+1
  # ffmpeg_kit_flutter: ^6.0.3
  # ffmpeg_kit_flutter_full_gpl: ^6.0.3

  media_kit: ^1.1.10+1                             # Primary package.
  video_player_media_kit: ^1.0.5
  media_kit_video: ^1.2.4                          # For video rendering.
  media_kit_libs_video: ^1.0.4                     # Native video dependencies.
  # media_kit_libs_audio: ^1.0.4                   # Native audio dependencies.
  media_kit_libs_linux: ^1.1.3
  media_kit_libs_windows_video: ^1.0.9
  media_kit_libs_android_video: ^1.3.6
  
  process_run: ^0.13.1
  # window_manager: ^0.3.7
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
